/**
 * Automations Queue Utility
 *
 * Handles enqueueing automation messages (email/SMS) with respect to quiet hours.
 * This is separate from message composition - it's purely for queueing messages
 * that were generated by automation triggers.
 */

import { supabase } from "./rest-client";
import { formatInTimeZone, fromZonedTime } from "date-fns-tz";

const NZ_TZ = "Pacific/Auckland";

/**
 * Apply quiet hours: if a scheduled time falls outside 9am-6pm NZT,
 * push it to 9am NZT the next morning.
 */
function applyQuietHours(scheduledFor: Date): Date {
  const nzHour = parseInt(formatInTimeZone(scheduledFor, NZ_TZ, "HH"), 10);
  if (nzHour >= 9 && nzHour < 18) {
    return scheduledFor;
  }
  // Schedule for 9am NZT next day if after 6pm, or same day 9am if before 9am
  const adjusted = new Date(scheduledFor);
  if (nzHour >= 18) {
    adjusted.setDate(adjusted.getDate() + 1);
  }
  const nzDate = formatInTimeZone(adjusted, NZ_TZ, "yyyy-MM-dd");
  return fromZonedTime(`${nzDate} 09:00:00`, NZ_TZ);
}

export interface EnqueueAutomationOptions {
  /** Template slug/identifier (e.g., "order-confirmation-email") */
  templateSlug: string;

  /** Contact ID to send to */
  contactId: string;

  /** Channel: email or SMS */
  channel: "email" | "sms";

  /** Template variables to interpolate */
  context: Record<string, string | number | boolean | null | undefined>;

  /** Optional: override scheduled time (defaults to now) */
  sendAt?: Date;

  /** Optional: bypass quiet hours (defaults to false) */
  bypassQuietHours?: boolean;
}

/**
 * Queue an automation message for sending.
 *
 * This function:
 * 1. Creates a message record in the messages table
 * 2. Creates a job_queue entry with type "send_email" or "send_sms"
 * 3. Applies quiet hours unless bypassQuietHours is true
 * 4. Returns the job ID
 *
 * @param options Configuration for the automation
 * @returns Job ID for tracking
 */
export async function enqueueAutomation(options: EnqueueAutomationOptions): Promise<string> {
  console.log("[enqueueAutomation] Starting", {
    templateSlug: options.templateSlug,
    contactId: options.contactId,
    channel: options.channel,
  });

  // Calculate scheduled time with quiet hours
  let scheduledFor = options.sendAt ?? new Date();
  if (!options.bypassQuietHours) {
    scheduledFor = applyQuietHours(scheduledFor);
    console.log("[enqueueAutomation] Applied quiet hours", { scheduledFor });
  }

  // Create message record
  const { data: message, error: messageError } = await supabase
    .from("messages")
    .insert({
      contact_id: options.contactId,
      direction: "outbound",
      channel: options.channel,
      body: options.context.body || "",
      body_html: options.context.bodyHtml || null,
      subject: options.context.subject || null,
      delivery_status: "queued",
    })
    .select()
    .single();

  if (messageError || !message) {
    console.error("[enqueueAutomation] Failed to create message", messageError);
    throw new Error(`Failed to create message: ${messageError?.message}`);
  }

  console.log("[enqueueAutomation] Message created", { messageId: message.id });

  // Send via Inngest
  const eventName = options.channel === "sms" ? "sms/send" : "email/send";
  const inngestKey = process.env.INNGEST_EVENT_KEY;

  if (inngestKey) {
    // Production: send via Inngest REST API
    await fetch("https://inn.gs/e/" + inngestKey, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name: eventName,
        data: {
          messageId: message.id,
          contactId: options.contactId,
        },
        id: `automation-${message.id}`,
      }),
    });
    console.log("[enqueueAutomation] Inngest event sent", { eventName, messageId: message.id });
  } else {
    // Fallback: insert into job_queue (for local dev without Inngest)
    const jobType = options.channel === "email" ? "send_email" : "send_sms";
    await supabase.from("job_queue").insert({
      type: jobType,
      payload: { messageId: message.id, contactId: options.contactId },
      scheduled_for: scheduledFor.toISOString(),
    });
    console.log("[enqueueAutomation] Job queued (fallback)", { jobType });
  }

  return message.id;
}
